name: Publish to NPM

on:
  release:
    types: [published]

permissions:
  contents: read

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    permissions:
      id-token: write

    steps:
      - name: Check out source code
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7

      - name: Set up node
        uses: actions/setup-node@1e60f620b9541d16bece96c5465dc8ee9832be0b # v4.0.3
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build library and publish
        run: |
          npm run build-lib
          cd ./dist/log4ngx
          npm publish --provenance --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.npm_token }}
