name: Publish to NPM

on:
  release:
    types: [published]

  workflow_dispatch:

permissions:
  contents: read

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    permissions:
      id-token: write

    steps:
      - name: Check out source code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      # The registry-url must be set for authentication to work on the npm publish step
      # Ref: https://github.com/actions/setup-node/issues/342#issuecomment-950119520
      - name: Set up node
        uses: actions/setup-node@39370e3970a6d050c480ffad4ff0ed4d3fdee5af # v4.1.0
        with:
          node-version: 20
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies
        run: npm ci

      - name: Build library and publish
        run: |
          npm run build-lib
          cd ./dist/log4ngx
          npm publish --provenance --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.npm_token }}
